services:
  database:
    image: postgres:16.3
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    restart: unless-stopped
